# Run poetry pre-commit hook to update requirements.txt
repos:
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.0  # add version here
  hooks:
    - id: poetry-check
      args: [ "--lock" ]
    - id: poetry-export
      args: ["--without-hashes"]

# Run ruff:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.9
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format # replaces Black

# Add pre-commit-hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
